### ISSUE TITLE
Is there any way to have the coverage table be generated from the outputFile (jest --json --outputFIle=results.json)?

### ISSUE THREAD

**Issue by sghsri** [MishaKav/jest-coverage-comment#15]
Hi. I'm currently using 2 actions, this one, and another one to add annotations to the code on test failure. The other action needs a JSON output file, while this one (to generate the coverage table PR comment) requires the raw console output to be put into a txt file. Maybe I'm mistaken, but it looks like only one of the 2 output formats are possible, either to a JSON file or to the console.

**Comment by MishaKav** [comment]
1. Already saw that you bump this bug in https://github.com/facebook/jest/issues/12427#issuecomment-1154161444
2. can you specify which `coverage table` you talk about? (there are 3 different tables like in the screenshot below)
![image](https://user-images.githubusercontent.com/289035/173407354-48aff0bf-acbe-4e59-84f1-a117dec23d84.png)

**Comment by sghsri** [comment]
Haha, good eye. 
My apologies, I'm talking specifically about Table #3

**Comment by MishaKav** [comment]
I think I found a workaround. It's not ideal, but until `jest` will fix this bug, you can use it.
In `package.json` I defined the scripts:
```json
"scripts": {
    "test": "jest",
    "test:coverage": "npm test -- --coverage",
    "test:coverage:tee": "npm run test:coverage --json --outputFile=results.json | tee ./covergate.txt"
}
```

then you can run `npm run test:coverage:tee`, it will run the tests and create `coverage.txt`, `results.json`

**Comment by sghsri** [comment]
The inverse is happening now, the coverage report is generating fine (and the coverage.txt has been found), but the result.json is not getting generated 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/13592854/173453420-71de1f65-a184-439d-99c1-401a9f8913c3.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/13592854/173453204-c4a725dc-93b3-40f2-b6f3-b8e3d26107bc.png">

**Comment by instil-spencerc** [comment]
In the event that someone lands here, looking for a way to prevent `| tee ./coverage.txt` from swallowing the failure of their test suite... I found that adding ` && exit ${PIPESTATUS[0]}` will properly show the action as failing (without generating the coverage report)
```
npx jest --coverage --coverageReporters json-summary | tee ./coverage.txt && exit ${PIPESTATUS[0]}
```

**Comment by MishaKav** [comment]
@instil-spencerc Thanks for the improvement of the command.
FYI:
When we do something like `| tee ./coverage.txt` we rely on output, which is not the best solution. 
A better solution is generating the report from a proper report like `coverage-summary.json`.
I added an option to generate coverage from the output as a "workaround` to make our lives easier when you want to test the action without changing too many configs.

I will update the README with `&& exit ${PIPESTATUS[0]` 👍
