### ISSUE TITLE
When create-new-comment is false, Report-only-changed-files should report the coverage for all files changed in the PR, not just the ones in the most recent commit

### ISSUE THREAD

**Issue by sghsri** [MishaKav/jest-coverage-comment#18]
This PR I have has a ton of changes.  and before the most recent commit was correctly showing the coverage amount for the changed files. 
![image](https://user-images.githubusercontent.com/13592854/176235146-d436d98e-14ad-466e-a9a1-287f02eed83a.png)

but after the most recent commit for some reason is showing no coverage. 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/13592854/176235280-f9dacdd7-9065-4b7c-815a-c70b3fdaf55a.png">

I have it so that its editing the comment every time (create-new-comment is false). In my opinion the expected behavior is that the comment should report coverage for files changed IN THE PR rather in the last commit when it is set like that

**Comment by MishaKav** [comment]
I run some tests and check your issue, what I see from my tests, and also [code](https://github.com/MishaKav/jest-coverage-comment/blob/main/src/changed-files.ts#L24-L26). It should report all changed files in PR (`pull_request` event). 
It looks that what you describe is a `push` event. You also have an option to see the commits.
Maybe you run this action on a `push` event?

![image](https://user-images.githubusercontent.com/289035/176284810-dd9cc309-a32e-4237-ab95-154ff2d1ca3c.png)

**Comment by norb-c** [comment]
I have the same issue here @MishaKav 
When `create-new-comment: false` and `report-only-changed-files: true`,  subsequent push events are not captured on the changed files.

**Comment by MishaKav** [comment]
comparing the base branch and the current branch may be done only in `pull_request`. 
When you do a `push` event GitHub **does not provide** on which PR you did the push. 
At the same time one branch may be open in dozens of PRs, this is why it's called `push` - it is relevant only on files that are `pushed` in this commit.

**Comment by norb-c** [comment]
OK, I didn't explain clearly.
We have a pull request created between say, the dev branch to the staging branch. 

Our configuration
```
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          report-only-changed-files: true
```

The coverage comment
![image](https://github.com/MishaKav/jest-coverage-comment/assets/24697877/ff82d4bc-887d-4864-ba41-8b552ebb2d19)

**Comment by MishaKav** [comment]
I still not got the issue that you describe, can you please read this comment https://github.com/MishaKav/jest-coverage-comment/issues/18#issuecomment-1169229154 carefully and check:
- On which event do you run `pull_request` or `push`?
- Do you see the `changed files` when you run the GitHub action?

**Comment by norb-c** [comment]
- We run on both pull_request and push
- Yes they were changed files



![image](https://github.com/MishaKav/jest-coverage-comment/assets/24697877/7791cb80-f7b1-4bae-8384-7b4b36fad1b6)

**Comment by MishaKav** [comment]
hm, it looks like the real issue, when I will have some time I will try to reproduce it locally and understand where the problem is. Will open the issue for now.

**Comment by MishaKav** [comment]
I successfully reproduced and understood what was going on.
The action can generate "the report" that you want only from `coverage-path` and can't do it from `coverage-summary-path`.
You can see this as a `warning` in your screenshot in line 46, that the `./coverage.txt` doesn't exist.
I'm suggesting you add something similar to (the last line is important):

```YAML
- name: Run Tests
  run: npm run coverage | tee ./coverage.txt

- name: Jest Coverage Comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    hide-comment: false
    create-new-comment: false
    hide-summary: false
    report-only-changed-files: true
    coverage-path: ./coverage.txt
```

**Comment by norb-c** [comment]
Thanks, The issue was that I didn't add `| tee ./coverage.txt` to my test command
