### ISSUE TITLE
bug: Branch and Function coverage in the summary

### ISSUE THREAD

**Issue by pavsaiprasad** [MishaKav/jest-coverage-comment#27]
Hi,

It appears that the coverage for Branch and Function are swapped in the Coverage Summary table i.e Branch shows Function coverage and viceversa. Would be great if you could fix it, or I could if you are happy for me to raise a PR.

https://github.com/MishaKav/jest-coverage-comment/blob/c90619da82ca2cf524544b6cf6144b8177c19023/src/summary.ts#L51

Thanks

**Comment by MishaKav** [comment]
Thanks for reporting the bug, I would be glad if you can fix this small issue. I'm happy when people contribute to open source )

**Comment by MishaKav** [comment]
I release the fix for the version, try to use the latest version:
 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
```
or 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@v1.0.15
```

Thanks for reporting the bug.
