### ISSUE TITLE
[feature request] support code hyperlinking in monorepo

### ISSUE THREAD

**Issue by bmccann36** [MishaKav/jest-coverage-comment#30]
Great gh action. Very well documented and easy to use.
I notice there is an option to get links to referenced files when you use `| tee ./coverage.txt`
Would it also be possible to support this when using the `multiple-files:` option ?

I am ambivalent as I type this because I like this action because of its simplicity. I tried some others that didn't work for me because they tried to do too much.

**Comment by MishaKav** [comment]
Thanks for the feedback, I’m glad that you find it useful. 

Currently `jest-coverage-path` support only a single file. I don't think that I will add this feature at all. 
GitHub comments are very limited, especially when the action posts rich HTML with links etc, so sometimes that is not enough space even for one report.

I can suggest you try running this action twice (each time for a different report) and pass the `create-new-comment: true`, in this way it should post you 2 different reports (2 different comments)

**Comment by bmccann36** [comment]
> Thanks for the feedback, I’m glad that you find it useful.
> 
> Currently `jest-coverage-path` support only a single file. I don't think that I will add this feature at all. GitHub comments are very limited, especially when the action posts rich HTML with links etc, so sometimes that is not enough space even for one report.
> 
> I can suggest you try running this action twice (each time for a different report) and pass the `create-new-comment: true`, in this way it should post you 2 different reports (2 different comments)

perfect I will do that
