### ISSUE TITLE
Actions returned the error when reading the coverage.txt file

### ISSUE THREAD

**Issue by hoangnguyen14** [MishaKav/jest-coverage-comment#31]
I setup the github actions workflow as below:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/86005951/195657349-970c2f98-a6cd-4427-913c-5d130f1ef601.png">
And when running on github, then I received the error message "Generating coverage report. Cannot read properties of undefined (reading 'length')".
<img width="873" alt="image" src="https://user-images.githubusercontent.com/86005951/195658139-063b4b04-a9a6-43bb-9480-ddf87c02c17e.png">

Could you please help to check the issue and let me know how to fix it or help to fix it?

Here is the attached coverage.txt file. which I downloaded from workflow

[coverage.txt](https://github.com/MishaKav/jest-coverage-comment/files/9778888/coverage.txt)

**Comment by MishaKav** [comment]
Thanks for the detailed issue.
I release the fix for that, try to use the latest version:
 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
```
or 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@v1.0.16
```

Thanks for reporting the bug.

**Comment by hoangnguyen14** [comment]
thank you so much for your support

**Comment by thuanndqsoft** [comment]
I still got this issue when running on github action.
![image](https://github.com/MishaKav/jest-coverage-comment/assets/83624291/7556cbec-8e8f-407e-b151-2ca3dc5c04a5)
