### ISSUE TITLE
Parse summary report. Cannot read properties of undefined (reading 'lines')

### ISSUE THREAD

**Issue by arthurgeron-work** [MishaKav/jest-coverage-comment#60]
File is read successfully but fails with "Parse summary report. Cannot read properties of undefined (reading 'lines')"
Jest version: 26.6.3

[coverage-final.json.zip](https://github.com/MishaKav/jest-coverage-comment/files/10387122/coverage-final.json.zip)

![Captura de Tela 2023-01-10 às 18 51 11](https://user-images.githubusercontent.com/71399856/211670012-6c7380dd-2cfb-4a02-a7ed-03b0939d57a9.png)

jest config:
```JavaScript

const requireJSON5 = require('require-json5');
const { compilerOptions } = requireJSON5('./tsconfig.json');

const config = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  setupFiles: ['<rootDir>/__tests__/setup.js', '<rootDir>/node_modules/react-native-gesture-handler/jestSetup.js'],
  transformIgnorePatterns: [],
  modulePathIgnorePatterns: [
    '<rootDir>/__tests__/index.ts',
    '<rootDir>/__tests__/setup.js',
    '<rootDir>/__tests__/utils/*',
    '<rootDir>/__tests__/mocks/*',
  ],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '\\.snap$'],
  testMatch: ['**/*.test.*'],
  coverageReporters: ['json', 'lcov'],
  collectCoverage: false,
  coveragePathIgnorePatterns: ['/[.]test[.].*$/gi'],
  collectCoverageFrom: [
    '<rootDir>/src/**/*.{js,jsx,ts,tsx}',
  ],
  roots: ['<rootDir>'],
  modulePaths: [compilerOptions.baseUrl],
  testResultsProcessor: 'jest-sonar-reporter',
  cacheDirectory: '.jest-cache',
  clearMocks: true,
  restoreMocks: true,
};

module.exports = config;

```

**Comment by MishaKav** [comment]
You pass the **wrong file**, this action doesn't support `coverage-final.json`, it supports the report of `coverage-summary.json`. 
These are different reports. To see the difference you can run for example `npx jest --coverage --coverageReporters json-summary` and see which report you should generate.

**or**

you can use the console output for the report, something like this:

```YAML
- name: Run tests
  run: npx jest --coverage | tee ./coverage.txt

- name: Jest Coverage Comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    coverage-path: ./coverage.txt
```
