### ISSUE TITLE
Write comment to a PR for push action.

### ISSUE THREAD

**Issue by jangot** [MishaKav/jest-coverage-comment#74]
I need to add/update a comment with code coverage when I do push to a branch. But it is possible only for `pull_request` and `pull_request_target` events.
I have checked your code and I see that for pushing you do only `createCommitComment`.
It would be grate if you add an opportunity to setup it some how.

I suggest to add additional option where I can define action type for publish a comment.
If there is no a PR you can skip publishing comment.

**Comment by MishaKav** [comment]
It's not a common usage, because every commit may related to more than 1 PR.
I will leave this issue open, if more people will vote for this, I will think about implementation.

**Comment by MishaKav** [comment]
After reviewing the issue, I've decided to close it as I currently don't have plans to implement this feature due to **low interest**.

If you have any further questions or concerns, please don't hesitate to let me know or reopen this issue.
Thanks you
