### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by moisespio** [MishaKav/jest-coverage-comment#78]
I have this action setup in a monorepo (Turbo) and the workflow is throwing an error after reading the `coverage.txt` file.

![Screenshot 2023-12-14 at 1 42 59 PM](https://github.com/MishaKav/jest-coverage-comment/assets/2017696/75493f20-6cc1-4294-bed8-1fc611918c95)

Output: [coverage.txt](https://github.com/MishaKav/jest-coverage-comment/files/13678164/coverage.txt)

**Comment by MishaKav** [comment]
Thanks for the output, I will take a look soon.

**Comment by moisespio** [comment]
I was actually missing an important thing in my `jest.config` file. This error occurs when you don't have the `text-summary` option. In my case, I only had the `text`.

`coverageReporters: ['json', 'json-summary', 'text', 'text-summary']`

Probably a good idea to mention this in the docs?

Thanks for looking into it though!
