### ISSUE TITLE
Add support to coverage-final.json

### ISSUE THREAD

**Issue by bwrutter** [MishaKav/jest-coverage-comment#82]
Hello, first of all, I would like to express gratitude for this excellent tool. I would appreciate it if, possible, the option to read and comment could be added when the file is coverage-final.json. It has a different structure from coverage-summary.json, but why coverage-final.json? I am using vitest.workspace, and it only exports in this format. Thank you very much!

Example:
[coverage-final.json](https://github.com/MishaKav/jest-coverage-comment/files/14563355/coverage-final.json)

**Comment by MishaKav** [comment]
Thanks, I'm glad that you found this action helpful.
You can try some working workaround to solve this issue, answered in StackOverflow: https://stackoverflow.com/questions/75835100/vitest-how-do-i-get-jest-compatible-coverage-summary-in-json
