### ISSUE TITLE
Allways creating a new comment when using a custom gitub-token

### ISSUE THREAD

**Issue by gabrielpires01** [MishaKav/jest-coverage-comment#83]
In my project i like to use a custom github-token proving a diferente user for the actions[bot], by doing so the createComment function is allways creatinh a new one instead of just updating. I have seen the other project for the pytest and there it doenst have the same problem. I can fork and make a PR fixing if you find relevant.
![image](https://github.com/MishaKav/jest-coverage-comment/assets/66154126/548b724a-edfb-482b-b39d-fdc1addeab77)

**Comment by MishaKav** [comment]
it makes sense and sounds reasonable, I would be glad if you could provide a fix for this.

**Comment by MishaKav** [comment]
Done in #96 #98
