### ISSUE TITLE
badge doesn't appear

### ISSUE THREAD

**Issue by jhonjtoloza** [MishaKav/jest-coverage-comment#84]
- name: ChatBot Coverage
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: services/chat-bot/coverage/coverage-summary.json
          title: ChatBot Coverage
          badge-title: chatbot-coverage
          hide-comment: false
          create-new-comment: false

Using these params

<img width="915" alt="Screenshot 2024-04-03 at 10 30 35 AM" src="https://github.com/MishaKav/jest-coverage-comment/assets/6846399/cc0f58f3-4183-4afb-a9e9-4fb761c8dede">

What am I doing wrong, or is this a real issue?

**Comment by MishaKav** [comment]
please share me the raw content of commit
(just do "edit comment" and copy the raw content)

**Comment by jhonjtoloza** [comment]
Thanks for answer here you are


# ChatBot Coverage

| Lines | Statements | Branches | Functions |
| --- | --- | --- | --- |
| <a href="https://github.com/TVS-LATAM/tvs-cloud-services/blob/09fe8eb506332b16e06b219f83a95b67f3dc8045/README.md"><img alt="chatbot-coverage: 40%" src="https://img.shields.io/badge/chatbot-coverage-40%25-orange.svg" /></a><br/> | 40.77% (904/2217) | 59.03% (49/83) | 47.36% (18/38) |

**Comment by MishaKav** [comment]
lol, this is a very strange bug around img-shields.
There is some reason that the `-` causes trouble.
You can easily fix this, by changing `-` (hyphen) to `_` (underscore) or ` ` (space)
```
badge-title: chatbot_coverage
```

this link will **not work**:
https://img.shields.io/badge/chatbot-coverage-40%25-orange.svg

this link **will work**:
https://img.shields.io/badge/chatbot_coverage-40%25-orange.svg

**Comment by jhonjtoloza** [comment]
That works, thanks you very much for your time.
