### ISSUE TITLE
Report only changed files not working

### ISSUE THREAD

**Issue by SirPhemmiey** [MishaKav/jest-coverage-comment#88]
Hello again, 

1. I get this error each time i set `report-only-changed-files: true` in my configuration

<img width="923" alt="Screenshot 2024-05-16 at 13 54 37" src="https://github.com/MishaKav/jest-coverage-comment/assets/22390818/9be8b5bb-98be-4b82-ba80-e2b87a4bc827">

Do you know how i can fix this?

2. Clicking on the files and lines here doesn't link to the corresponding location. This might be a long stretch and it's not a make or break for me but do you know how i can possibly get it to work correctly? 
<img width="1156" alt="Screenshot 2024-05-16 at 12 45 49" src="https://github.com/MishaKav/jest-coverage-comment/assets/22390818/bb1f85cc-5040-4ba5-a8ae-7b02f3ad9ebc">

**Comment by SirPhemmiey** [comment]
Thank you for the references. 

On #2, i'm running in a monorepo and the structure is like apps/<app-name>/src/**

If i pass`coverage-path-prefix: apps/`, it will go to somewhere like `apps/src/components/renderer.element.ts` instead of `apps/<app-name>/src/components/renderer.element.ts`

this is probably out of scope of your library, but i'm happy to hear your thoughts

**Comment by MishaKav** [comment]
I think you may run this github-action several times, and each time generate a report for a different app with a specific prefix (you will get a different comment for each app - which is a good approach I think), because even if you use multiple-files, your report will be generated for one app.
