### ISSUE TITLE
[Feature] Dynamic multi line comment 

### ISSUE THREAD

**Issue by Tallyb** [MishaKav/jest-coverage-comment#91]
Allow passing multi line as a string. 
The purpose is to create a dynamic comment, and generating a new line is problematic. A separator like @@ could be useful.

**Comment by MishaKav** [comment]
Can you provide a more detailed example: how to use it, what you want to achieve etc?

**Comment by MishaKav** [comment]
@Tallyb can you please update?

**Comment by MishaKav** [comment]
Close this one, because I don't understand the purpose of this feature, and is no answer from the author of the issue.
Fill free to create a new one with more details/examples/interfaces etc.
